### ISSUE TITLE
Unable to start vr-xrv

### ISSUE THREAD

**Issue by lamehost** [plajjan/vrnetlab#143]
Hello,

I'm having troubles with vr-xrv.
The emulated router eventually boots, but start() in vrnetlab.py tries to telnet to localhost:5000 too soon that is enough to make it fail:

```
$  docker run --rm -i -t --name vr1 --privileged vr-xrv:5.3.3
2017-06-23 14:11:19,767: vrnetlab   DEBUG    Starting vrnetlab XRV
2017-06-23 14:11:19,767: vrnetlab   DEBUG    VMs: [<__main__.XRV_vm object at 0x7fecc5bfb128>]
2017-06-23 14:11:19,771: vrnetlab   DEBUG    VM not started; starting!
2017-06-23 14:11:19,771: vrnetlab   INFO     Starting XRV_vm
2017-06-23 14:11:19,773: vrnetlab   DEBUG    ['qemu-system-x86_64', '-enable-kvm', '-display', 'none', '-machine', 'pc', '-monitor', 'tcp:0.0.0.0:4000,server,nowait', '-m', '3072', '-serial', 'telnet:0.0.0.0:5000,server,nowait', '-drive', 'if=ide,file=/iosxrv-demo-5.3.3.vmdk', '-device', 'pci-bridge,chassis_nr=1,id=pci.1', '-device', 'pci-bridge,chassis_nr=2,id=pci.2', '-device', 'pci-bridge,chassis_nr=3,id=pci.3', '-device', 'pci-bridge,chassis_nr=4,id=pci.4', '-device', 'pci-bridge,chassis_nr=5,id=pci.5', '-device', 'e1000,netdev=p00,mac=52:54:00:0e:72:00', '-netdev', 'user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=tcp::2830-10.0.0.15:830', '-device', 'e1000,netdev=p01,mac=52:54:00:11:47:01,bus=pci.1,addr=0x2', '-netdev', 'socket,id=p01,listen=:10001', '-device', 'e1000,netdev=p02,mac=52:54:00:af:ff:02,bus=pci.1,addr=0x3', '-netdev', 'socket,id=p02,listen=:10002', '-device', 'e1000,netdev=p03,mac=52:54:00:5c:dc:03,bus=pci.1,addr=0x4', '-netdev', 'socket,id=p03,listen=:10003', '-device', 'e1000,netdev=p04,mac=52:54:00:67:42:04,bus=pci.1,addr=0x5', '-netdev', 'socket,id=p04,listen=:10004', '-device', 'e1000,netdev=p05,mac=52:54:00:4d:5a:05,bus=pci.1,addr=0x6', '-netdev', 'socket,id=p05,listen=:10005', '-device', 'e1000,netdev=p06,mac=52:54:00:16:36:06,bus=pci.1,addr=0x7', '-netdev', 'socket,id=p06,listen=:10006', '-device', 'e1000,netdev=p07,mac=52:54:00:08:e5:07,bus=pci.1,addr=0x8', '-netdev', 'socket,id=p07,listen=:10007', '-device', 'e1000,netdev=p08,mac=52:54:00:be:c4:08,bus=pci.1,addr=0x9', '-netdev', 'socket,id=p08,listen=:10008', '-device', 'e1000,netdev=p09,mac=52:54:00:21:9e:09,bus=pci.1,addr=0xa', '-netdev', 'socket,id=p09,listen=:10009', '-device', 'e1000,netdev=p10,mac=52:54:00:0a:dd:0a,bus=pci.1,addr=0xb', '-netdev', 'socket,id=p10,listen=:10010', '-device', 'e1000,netdev=p11,mac=52:54:00:e1:a5:0b,bus=pci.1,addr=0xc', '-netdev', 'socket,id=p11,listen=:10011', '-device', 'e1000,netdev=p12,mac=52:54:00:3e:12:0c,bus=pci.1,addr=0xd', '-netdev', 'socket,id=p12,listen=:10012', '-device', 'e1000,netdev=p13,mac=52:54:00:29:95:0d,bus=pci.1,addr=0xe', '-netdev', 'socket,id=p13,listen=:10013', '-device', 'e1000,netdev=p14,mac=52:54:00:ca:a6:0e,bus=pci.1,addr=0xf', '-netdev', 'socket,id=p14,listen=:10014', '-device', 'e1000,netdev=p15,mac=52:54:00:97:22:0f,bus=pci.1,addr=0x10', '-netdev', 'socket,id=p15,listen=:10015', '-device', 'e1000,netdev=p16,mac=52:54:00:01:76:10,bus=pci.1,addr=0x11', '-netdev', 'socket,id=p16,listen=:10016', '-device', 'e1000,netdev=p17,mac=52:54:00:15:0e:11,bus=pci.1,addr=0x12', '-netdev', 'socket,id=p17,listen=:10017', '-device', 'e1000,netdev=p18,mac=52:54:00:3c:92:12,bus=pci.1,addr=0x13', '-netdev', 'socket,id=p18,listen=:10018', '-device', 'e1000,netdev=p19,mac=52:54:00:29:38:13,bus=pci.1,addr=0x14', '-netdev', 'socket,id=p19,listen=:10019', '-device', 'e1000,netdev=p20,mac=52:54:00:a9:9c:14,bus=pci.1,addr=0x15', '-netdev', 'socket,id=p20,listen=:10020', '-device', 'e1000,netdev=p21,mac=52:54:00:9a:35:15,bus=pci.1,addr=0x16', '-netdev', 'socket,id=p21,listen=:10021', '-device', 'e1000,netdev=p22,mac=52:54:00:f3:96:16,bus=pci.1,addr=0x17', '-netdev', 'socket,id=p22,listen=:10022', '-device', 'e1000,netdev=p23,mac=52:54:00:0f:c2:17,bus=pci.1,addr=0x18', '-netdev', 'socket,id=p23,listen=:10023', '-device', 'e1000,netdev=p24,mac=52:54:00:c7:2d:18,bus=pci.1,addr=0x19', '-netdev', 'socket,id=p24,listen=:10024', '-device', 'e1000,netdev=p25,mac=52:54:00:d0:e3:19,bus=pci.1,addr=0x1a', '-netdev', 'socket,id=p25,listen=:10025', '-device', 'e1000,netdev=p26,mac=52:54:00:32:26:1a,bus=pci.2,addr=0x1', '-netdev', 'socket,id=p26,listen=:10026', '-device', 'e1000,netdev=p27,mac=52:54:00:7f:5b:1b,bus=pci.2,addr=0x2', '-netdev', 'socket,id=p27,listen=:10027', '-device', 'e1000,netdev=p28,mac=52:54:00:1f:61:1c,bus=pci.2,addr=0x3', '-netdev', 'socket,id=p28,listen=:10028', '-device', 'e1000,netdev=p29,mac=52:54:00:7e:4a:1d,bus=pci.2,addr=0x4', '-netdev', 'socket,id=p29,listen=:10029', '-device', 'e1000,netdev=p30,mac=52:54:00:13:42:1e,bus=pci.2,addr=0x5', '-netdev', 'socket,id=p30,listen=:10030', '-device', 'e1000,netdev=p31,mac=52:54:00:99:3c:1f,bus=pci.2,addr=0x6', '-netdev', 'socket,id=p31,listen=:10031', '-device', 'e1000,netdev=p32,mac=52:54:00:64:75:20,bus=pci.2,addr=0x7', '-netdev', 'socket,id=p32,listen=:10032', '-device', 'e1000,netdev=p33,mac=52:54:00:89:d7:21,bus=pci.2,addr=0x8', '-netdev', 'socket,id=p33,listen=:10033', '-device', 'e1000,netdev=p34,mac=52:54:00:6f:82:22,bus=pci.2,addr=0x9', '-netdev', 'socket,id=p34,listen=:10034', '-device', 'e1000,netdev=p35,mac=52:54:00:d6:b3:23,bus=pci.2,addr=0xa', '-netdev', 'socket,id=p35,listen=:10035', '-device', 'e1000,netdev=p36,mac=52:54:00:0a:a4:24,bus=pci.2,addr=0xb', '-netdev', 'socket,id=p36,listen=:10036', '-device', 'e1000,netdev=p37,mac=52:54:00:36:97:25,bus=pci.2,addr=0xc', '-netdev', 'socket,id=p37,listen=:10037', '-device', 'e1000,netdev=p38,mac=52:54:00:e2:7c:26,bus=pci.2,addr=0xd', '-netdev', 'socket,id=p38,listen=:10038', '-device', 'e1000,netdev=p39,mac=52:54:00:cb:71:27,bus=pci.2,addr=0xe', '-netdev', 'socket,id=p39,listen=:10039', '-device', 'e1000,netdev=p40,mac=52:54:00:46:82:28,bus=pci.2,addr=0xf', '-netdev', 'socket,id=p40,listen=:10040', '-device', 'e1000,netdev=p41,mac=52:54:00:0b:7a:29,bus=pci.2,addr=0x10', '-netdev', 'socket,id=p41,listen=:10041', '-device', 'e1000,netdev=p42,mac=52:54:00:56:42:2a,bus=pci.2,addr=0x11', '-netdev', 'socket,id=p42,listen=:10042', '-device', 'e1000,netdev=p43,mac=52:54:00:11:85:2b,bus=pci.2,addr=0x12', '-netdev', 'socket,id=p43,listen=:10043', '-device', 'e1000,netdev=p44,mac=52:54:00:d3:50:2c,bus=pci.2,addr=0x13', '-netdev', 'socket,id=p44,listen=:10044', '-device', 'e1000,netdev=p45,mac=52:54:00:1d:87:2d,bus=pci.2,addr=0x14', '-netdev', 'socket,id=p45,listen=:10045', '-device', 'e1000,netdev=p46,mac=52:54:00:e5:1f:2e,bus=pci.2,addr=0x15', '-netdev', 'socket,id=p46,listen=:10046', '-device', 'e1000,netdev=p47,mac=52:54:00:9c:3a:2f,bus=pci.2,addr=0x16', '-netdev', 'socket,id=p47,listen=:10047', '-device', 'e1000,netdev=p48,mac=52:54:00:4f:dc:30,bus=pci.2,addr=0x17', '-netdev', 'socket,id=p48,listen=:10048', '-device', 'e1000,netdev=p49,mac=52:54:00:06:1a:31,bus=pci.2,addr=0x18', '-netdev', 'socket,id=p49,listen=:10049', '-device', 'e1000,netdev=p50,mac=52:54:00:4a:27:32,bus=pci.2,addr=0x19', '-netdev', 'socket,id=p50,listen=:10050', '-device', 'e1000,netdev=p51,mac=52:54:00:23:c5:33,bus=pci.2,addr=0x1a', '-netdev', 'socket,id=p51,listen=:10051', '-device', 'e1000,netdev=p52,mac=52:54:00:9f:85:34,bus=pci.3,addr=0x1', '-netdev', 'socket,id=p52,listen=:10052', '-device', 'e1000,netdev=p53,mac=52:54:00:d8:d2:35,bus=pci.3,addr=0x2', '-netdev', 'socket,id=p53,listen=:10053', '-device', 'e1000,netdev=p54,mac=52:54:00:56:99:36,bus=pci.3,addr=0x3', '-netdev', 'socket,id=p54,listen=:10054', '-device', 'e1000,netdev=p55,mac=52:54:00:7e:63:37,bus=pci.3,addr=0x4', '-netdev', 'socket,id=p55,listen=:10055', '-device', 'e1000,netdev=p56,mac=52:54:00:56:92:38,bus=pci.3,addr=0x5', '-netdev', 'socket,id=p56,listen=:10056', '-device', 'e1000,netdev=p57,mac=52:54:00:81:90:39,bus=pci.3,addr=0x6', '-netdev', 'socket,id=p57,listen=:10057', '-device', 'e1000,netdev=p58,mac=52:54:00:f5:d3:3a,bus=pci.3,addr=0x7', '-netdev', 'socket,id=p58,listen=:10058', '-device', 'e1000,netdev=p59,mac=52:54:00:2a:43:3b,bus=pci.3,addr=0x8', '-netdev', 'socket,id=p59,listen=:10059', '-device', 'e1000,netdev=p60,mac=52:54:00:3c:e9:3c,bus=pci.3,addr=0x9', '-netdev', 'socket,id=p60,listen=:10060', '-device', 'e1000,netdev=p61,mac=52:54:00:ee:a2:3d,bus=pci.3,addr=0xa', '-netdev', 'socket,id=p61,listen=:10061', '-device', 'e1000,netdev=p62,mac=52:54:00:72:88:3e,bus=pci.3,addr=0xb', '-netdev', 'socket,id=p62,listen=:10062', '-device', 'e1000,netdev=p63,mac=52:54:00:70:ea:3f,bus=pci.3,addr=0xc', '-netdev', 'socket,id=p63,listen=:10063', '-device', 'e1000,netdev=p64,mac=52:54:00:b5:98:40,bus=pci.3,addr=0xd', '-netdev', 'socket,id=p64,listen=:10064', '-device', 'e1000,netdev=p65,mac=52:54:00:21:eb:41,bus=pci.3,addr=0xe', '-netdev', 'socket,id=p65,listen=:10065', '-device', 'e1000,netdev=p66,mac=52:54:00:cb:b3:42,bus=pci.3,addr=0xf', '-netdev', 'socket,id=p66,listen=:10066', '-device', 'e1000,netdev=p67,mac=52:54:00:0d:6d:43,bus=pci.3,addr=0x10', '-netdev', 'socket,id=p67,listen=:10067', '-device', 'e1000,netdev=p68,mac=52:54:00:3c:2a:44,bus=pci.3,addr=0x11', '-netdev', 'socket,id=p68,listen=:10068', '-device', 'e1000,netdev=p69,mac=52:54:00:42:51:45,bus=pci.3,addr=0x12', '-netdev', 'socket,id=p69,listen=:10069', '-device', 'e1000,netdev=p70,mac=52:54:00:89:36:46,bus=pci.3,addr=0x13', '-netdev', 'socket,id=p70,listen=:10070', '-device', 'e1000,netdev=p71,mac=52:54:00:05:36:47,bus=pci.3,addr=0x14', '-netdev', 'socket,id=p71,listen=:10071', '-device', 'e1000,netdev=p72,mac=52:54:00:39:fb:48,bus=pci.3,addr=0x15', '-netdev', 'socket,id=p72,listen=:10072', '-device', 'e1000,netdev=p73,mac=52:54:00:0f:f2:49,bus=pci.3,addr=0x16', '-netdev', 'socket,id=p73,listen=:10073', '-device', 'e1000,netdev=p74,mac=52:54:00:6c:c1:4a,bus=pci.3,addr=0x17', '-netdev', 'socket,id=p74,listen=:10074', '-device', 'e1000,netdev=p75,mac=52:54:00:97:ca:4b,bus=pci.3,addr=0x18', '-netdev', 'socket,id=p75,listen=:10075', '-device', 'e1000,netdev=p76,mac=52:54:00:60:c7:4c,bus=pci.3,addr=0x19', '-netdev', 'socket,id=p76,listen=:10076', '-device', 'e1000,netdev=p77,mac=52:54:00:ea:10:4d,bus=pci.3,addr=0x1a', '-netdev', 'socket,id=p77,listen=:10077', '-device', 'e1000,netdev=p78,mac=52:54:00:10:1f:4e,bus=pci.4,addr=0x1', '-netdev', 'socket,id=p78,listen=:10078', '-device', 'e1000,netdev=p79,mac=52:54:00:8b:13:4f,bus=pci.4,addr=0x2', '-netdev', 'socket,id=p79,listen=:10079', '-device', 'e1000,netdev=p80,mac=52:54:00:e0:bf:50,bus=pci.4,addr=0x3', '-netdev', 'socket,id=p80,listen=:10080', '-device', 'e1000,netdev=p81,mac=52:54:00:0a:61:51,bus=pci.4,addr=0x4', '-netdev', 'socket,id=p81,listen=:10081', '-device', 'e1000,netdev=p82,mac=52:54:00:2a:d3:52,bus=pci.4,addr=0x5', '-netdev', 'socket,id=p82,listen=:10082', '-device', 'e1000,netdev=p83,mac=52:54:00:58:cb:53,bus=pci.4,addr=0x6', '-netdev', 'socket,id=p83,listen=:10083', '-device', 'e1000,netdev=p84,mac=52:54:00:9a:a2:54,bus=pci.4,addr=0x7', '-netdev', 'socket,id=p84,listen=:10084', '-device', 'e1000,netdev=p85,mac=52:54:00:20:9d:55,bus=pci.4,addr=0x8', '-netdev', 'socket,id=p85,listen=:10085', '-device', 'e1000,netdev=p86,mac=52:54:00:2a:64:56,bus=pci.4,addr=0x9', '-netdev', 'socket,id=p86,listen=:10086', '-device', 'e1000,netdev=p87,mac=52:54:00:b8:21:57,bus=pci.4,addr=0xa', '-netdev', 'socket,id=p87,listen=:10087', '-device', 'e1000,netdev=p88,mac=52:54:00:19:0e:58,bus=pci.4,addr=0xb', '-netdev', 'socket,id=p88,listen=:10088', '-device', 'e1000,netdev=p89,mac=52:54:00:c0:3a:59,bus=pci.4,addr=0xc', '-netdev', 'socket,id=p89,listen=:10089', '-device', 'e1000,netdev=p90,mac=52:54:00:b5:c5:5a,bus=pci.4,addr=0xd', '-netdev', 'socket,id=p90,listen=:10090', '-device', 'e1000,netdev=p91,mac=52:54:00:80:cf:5b,bus=pci.4,addr=0xe', '-netdev', 'socket,id=p91,listen=:10091', '-device', 'e1000,netdev=p92,mac=52:54:00:a3:ef:5c,bus=pci.4,addr=0xf', '-netdev', 'socket,id=p92,listen=:10092', '-device', 'e1000,netdev=p93,mac=52:54:00:19:cb:5d,bus=pci.4,addr=0x10', '-netdev', 'socket,id=p93,listen=:10093', '-device', 'e1000,netdev=p94,mac=52:54:00:21:72:5e,bus=pci.4,addr=0x11', '-netdev', 'socket,id=p94,listen=:10094', '-device', 'e1000,netdev=p95,mac=52:54:00:ed:f2:5f,bus=pci.4,addr=0x12', '-netdev', 'socket,id=p95,listen=:10095', '-device', 'e1000,netdev=p96,mac=52:54:00:a0:a4:60,bus=pci.4,addr=0x13', '-netdev', 'socket,id=p96,listen=:10096', '-device', 'e1000,netdev=p97,mac=52:54:00:bf:a6:61,bus=pci.4,addr=0x14', '-netdev', 'socket,id=p97,listen=:10097', '-device', 'e1000,netdev=p98,mac=52:54:00:ef:0d:62,bus=pci.4,addr=0x15', '-netdev', 'socket,id=p98,listen=:10098', '-device', 'e1000,netdev=p99,mac=52:54:00:a8:c2:63,bus=pci.4,addr=0x16', '-netdev', 'socket,id=p99,listen=:10099', '-device', 'e1000,netdev=p100,mac=52:54:00:ba:08:64,bus=pci.4,addr=0x17', '-netdev', 'socket,id=p100,listen=:100100', '-device', 'e1000,netdev=p101,mac=52:54:00:62:40:65,bus=pci.4,addr=0x18', '-netdev', 'socket,id=p101,listen=:100101', '-device', 'e1000,netdev=p102,mac=52:54:00:fa:e1:66,bus=pci.4,addr=0x19', '-netdev', 'socket,id=p102,listen=:100102', '-device', 'e1000,netdev=p103,mac=52:54:00:24:d5:67,bus=pci.4,addr=0x1a', '-netdev', 'socket,id=p103,listen=:100103', '-device', 'e1000,netdev=p104,mac=52:54:00:e7:cb:68,bus=pci.5,addr=0x1', '-netdev', 'socket,id=p104,listen=:100104', '-device', 'e1000,netdev=p105,mac=52:54:00:56:2b:69,bus=pci.5,addr=0x2', '-netdev', 'socket,id=p105,listen=:100105', '-device', 'e1000,netdev=p106,mac=52:54:00:bf:87:6a,bus=pci.5,addr=0x3', '-netdev', 'socket,id=p106,listen=:100106', '-device', 'e1000,netdev=p107,mac=52:54:00:57:87:6b,bus=pci.5,addr=0x4', '-netdev', 'socket,id=p107,listen=:100107', '-device', 'e1000,netdev=p108,mac=52:54:00:25:1c:6c,bus=pci.5,addr=0x5', '-netdev', 'socket,id=p108,listen=:100108', '-device', 'e1000,netdev=p109,mac=52:54:00:d8:ec:6d,bus=pci.5,addr=0x6', '-netdev', 'socket,id=p109,listen=:100109', '-device', 'e1000,netdev=p110,mac=52:54:00:1b:0b:6e,bus=pci.5,addr=0x7', '-netdev', 'socket,id=p110,listen=:100110', '-device', 'e1000,netdev=p111,mac=52:54:00:67:c9:6f,bus=pci.5,addr=0x8', '-netdev', 'socket,id=p111,listen=:100111', '-device', 'e1000,netdev=p112,mac=52:54:00:aa:b0:70,bus=pci.5,addr=0x9', '-netdev', 'socket,id=p112,listen=:100112', '-device', 'e1000,netdev=p113,mac=52:54:00:91:98:71,bus=pci.5,addr=0xa', '-netdev', 'socket,id=p113,listen=:100113', '-device', 'e1000,netdev=p114,mac=52:54:00:9f:ab:72,bus=pci.5,addr=0xb', '-netdev', 'socket,id=p114,listen=:100114', '-device', 'e1000,netdev=p115,mac=52:54:00:0d:20:73,bus=pci.5,addr=0xc', '-netdev', 'socket,id=p115,listen=:100115', '-device', 'e1000,netdev=p116,mac=52:54:00:ca:4b:74,bus=pci.5,addr=0xd', '-netdev', 'socket,id=p116,listen=:100116', '-device', 'e1000,netdev=p117,mac=52:54:00:9e:1f:75,bus=pci.5,addr=0xe', '-netdev', 'socket,id=p117,listen=:100117', '-device', 'e1000,netdev=p118,mac=52:54:00:39:62:76,bus=pci.5,addr=0xf', '-netdev', 'socket,id=p118,listen=:100118', '-device', 'e1000,netdev=p119,mac=52:54:00:61:1e:77,bus=pci.5,addr=0x10', '-netdev', 'socket,id=p119,listen=:100119', '-device', 'e1000,netdev=p120,mac=52:54:00:fd:d1:78,bus=pci.5,addr=0x11', '-netdev', 'socket,id=p120,listen=:100120', '-device', 'e1000,netdev=p121,mac=52:54:00:42:9c:79,bus=pci.5,addr=0x12', '-netdev', 'socket,id=p121,listen=:100121', '-device', 'e1000,netdev=p122,mac=52:54:00:ed:92:7a,bus=pci.5,addr=0x13', '-netdev', 'socket,id=p122,listen=:100122', '-device', 'e1000,netdev=p123,mac=52:54:00:80:7c:7b,bus=pci.5,addr=0x14', '-netdev', 'socket,id=p123,listen=:100123', '-device', 'e1000,netdev=p124,mac=52:54:00:aa:a2:7c,bus=pci.5,addr=0x15', '-netdev', 'socket,id=p124,listen=:100124', '-device', 'e1000,netdev=p125,mac=52:54:00:30:a4:7d,bus=pci.5,addr=0x16', '-netdev', 'socket,id=p125,listen=:100125', '-device', 'e1000,netdev=p126,mac=52:54:00:b6:64:7e,bus=pci.5,addr=0x17', '-netdev', 'socket,id=p126,listen=:100126', '-device', 'e1000,netdev=p127,mac=52:54:00:db:e9:7f,bus=pci.5,addr=0x18', '-netdev', 'socket,id=p127,listen=:100127', '-device', 'e1000,netdev=p128,mac=52:54:00:0f:5e:80,bus=pci.5,addr=0x19', '-netdev', 'socket,id=p128,listen=:100128']
Traceback (most recent call last):
  File "/launch.py", line 190, in <module>
    vr.start()
  File "/vrnetlab.py", line 269, in start
    vm.work()
  File "/vrnetlab.py", line 207, in work
    self.check_qemu()
  File "/vrnetlab.py", line 223, in check_qemu
    self.start()
  File "/vrnetlab.py", line 116, in start
    self.tn = telnetlib.Telnet("127.0.0.1", 5000 + self.num)
  File "/usr/lib/python3.5/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

I added this patch to my local report as temporary workaround and everything works
```
diff --git a/common/vrnetlab.py b/common/vrnetlab.py
index fd667e4..e4099d4 100644
--- a/common/vrnetlab.py
+++ b/common/vrnetlab.py
@@ -7,6 +7,7 @@ import os
 import random
 import subprocess
 import telnetlib
+from time import sleep
 
 def gen_mac(last_octet=None):
     """ Generate a random MAC address that is in the qemu OUI space and that
@@ -111,6 +112,7 @@ class VM:
             pass
 
         self.qm = telnetlib.Telnet("127.0.0.1", 4000 + self.num)
+        sleep(5)
         self.tn = telnetlib.Telnet("127.0.0.1", 5000 + self.num)
```

Thank you

Regards

**Comment by plajjan** [comment]
That is weird. It's qemu that is listening to port 5000 (not the router - the router only sees a serial device) so it should listen as soon as it's started. We even sleep for 2 seconds at https://github.com/plajjan/vrnetlab/blob/master/common/vrnetlab.py#L107 waiting for output, so in effect you are now at 7 seconds sleep. Is your computer slow?

**Comment by plajjan** [comment]
We could instead retry the connection until it succeeds...

**Comment by lamehost** [comment]
Hello,

Raising timeout at https://github.com/plajjan/vrnetlab/blob/master/common/vrnetlab.py#L110 to 5 seconds definitely works even without the patch.

Regards

**Comment by plajjan** [comment]
22e0097dffe787bc955f64ba2680b420ccc9fbd9 should fix it! closing :)
