### ISSUE TITLE
vmx crash: ValueError: Invalid file object

### ISSUE THREAD

**Issue by htj** [plajjan/vrnetlab#181]
Anyone else seeing this:

```
2018-07-18 08:43:07,783: launch     INFO     matched login prompt
2018-07-18 08:43:07,783: launch     DEBUG    writing to serial console: root
2018-07-18 08:43:09,787: launch     DEBUG    writing to serial console: cli
2018-07-18 08:43:09,883: launch     DEBUG    writing to serial console: configure
2018-07-18 08:43:09,926: launch     DEBUG    writing to serial console: set chassis fpc 0 pic 0 number-of-ports 96
2018-07-18 08:43:09,970: launch     DEBUG    writing to serial console: set system services ssh
2018-07-18 08:43:10,018: launch     DEBUG    writing to serial console: set system services netconf ssh
2018-07-18 08:43:10,065: launch     DEBUG    writing to serial console: set system services netconf rfc-compliant
2018-07-18 08:43:10,110: launch     DEBUG    writing to serial console: set system login user vrnetlab class super-user authentication plain-text-password
2018-07-18 08:43:10,158: launch     DEBUG    writing to serial console: VR-netlab9
2018-07-18 08:43:10,205: launch     DEBUG    writing to serial console: VR-netlab9
2018-07-18 08:43:10,257: launch     DEBUG    writing to serial console: set system root-authentication plain-text-password
2018-07-18 08:43:10,310: launch     DEBUG    writing to serial console: VR-netlab9
2018-07-18 08:43:10,357: launch     DEBUG    writing to serial console: VR-netlab9
2018-07-18 08:43:10,405: launch     DEBUG    writing to serial console: set interfaces fxp0 unit 0 family inet address 10.0.0.15/24
2018-07-18 08:43:10,450: launch     DEBUG    writing to serial console: commit
2018-07-18 08:43:12,988: launch     DEBUG    writing to serial console: exit
2018-07-18 08:43:12,989: launch     INFO     Startup complete in: 0:03:03.554954
2018-07-18 08:44:30,326: vrnetlab   INFO     STDOUT:
2018-07-18 08:44:30,335: vrnetlab   INFO     STDERR:
Traceback (most recent call last):
  File "/launch.py", line 329, in <module>
    vr.start()
  File "/vrnetlab.py", line 317, in start
    vm.work()
  File "/vrnetlab.py", line 254, in work
    self.check_qemu()
  File "/vrnetlab.py", line 274, in check_qemu
    outs, errs = self.p.communicate(timeout=1)
  File "/usr/lib/python3.5/subprocess.py", line 801, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1437, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/usr/lib/python3.5/selectors.py", line 351, in register
    key = super().register(fileobj, events, data)
  File "/usr/lib/python3.5/selectors.py", line 237, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/usr/lib/python3.5/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib/python3.5/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.TextIOWrapper name=7 encoding='ANSI_X3.4-1968'>
```

**Comment by plajjan** [comment]
Nope. But invalid file object... so I guess the VM has died already and that's why we can't read the stdout handler? Can you start the machine with `--trace` and maybe you'll get a little more output before it dies?

**Comment by plajjan** [comment]
Funny, it just happened to me. I'm trying out kubernetes so I don't really know what I'm doing but it resulted in this:
```
2018-11-21 22:33:40,916: launch     INFO     Number of NICS: 5
2018-11-21 22:33:40,916: vrnetlab   DEBUG    Creating overlay disk image
2018-11-21 22:33:40,931: launch     INFO     License file found for UUID 4100630c-2539-408c-8669-e8a90deda50a with start date None
device int_cp already exists; can't create bridge with the same name
2018-11-21 22:33:40,934: vrnetlab   DEBUG    Starting vrnetlab SROS
2018-11-21 22:33:40,934: vrnetlab   DEBUG    VMs: [<__main__.SROS_integrated object at 0x7f4c6728be10>]
2018/11/21 22:33:40 socat[11] E bind(5, {AF=2 0.0.0.0:22}, 16): Address already in use
2018-11-21 22:33:40,938: vrnetlab   DEBUG    VM not started; starting!
2018-11-21 22:33:40,938: vrnetlab   INFO     Starting SROS_integrated
2018-11-21 22:33:40,938: vrnetlab   DEBUG    ['qemu-system-x86_64', '-enable-kvm', '-display', 'none', '-machine', 'pc', '-monitor', 'tcp:0.0.0.0:4000,server,nowait', '-m', '4096', '-serial', 'telnet:0.0.0.0:5000,server,nowait', '-drive', 'if=ide,file=/sros-overlay.qcow2', '-uuid', '4100630c-2539-408c-8669-e8a90deda50a', '-smbios', 'type=1,product=TIMOS:address=10.0.0.15/24@active license-file=tftp://10.0.0.2/license.txt slot=A chassis=SR-c12 card=cfm-xp-b mda/1=m20-1gb-xp-sfp', '-device', 'pci-bridge,chassis_nr=1,id=pci.1', '-device', 'e1000,netdev=p00,mac=52:54:00:c6:b9:00', '-netdev', 'user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830', '-device', 'e1000,netdev=dummy0,mac=52:54:00:11:2f:01', '-netdev', 'tap,ifname=dummy0,id=dummy0,script=no,downscript=no', '-device', 'e1000,netdev=p01,mac=52:54:00:04:b5:01,bus=pci.1,addr=0x2', '-netdev', 'socket,id=p01,listen=:10001', '-device', 'e1000,netdev=p02,mac=52:54:00:10:a2:02,bus=pci.1,addr=0x3', '-netdev', 'socket,id=p02,listen=:10002', '-device', 'e1000,netdev=p03,mac=52:54:00:2b:c7:03,bus=pci.1,addr=0x4', '-netdev', 'socket,id=p03,listen=:10003', '-device', 'e1000,netdev=p04,mac=52:54:00:ff:5e:04,bus=pci.1,addr=0x5', '-netdev', 'socket,id=p04,listen=:10004', '-device', 'e1000,netdev=p05,mac=52:54:00:b5:3a:05,bus=pci.1,addr=0x6', '-netdev', 'socket,id=p05,listen=:10005']
2018/11/21 22:33:40 socat[13] E bind(5, {AF=2 0.0.0.0:830}, 16): Address already in use
2018-11-21 22:33:40,959: vrnetlab   INFO     STDOUT: 
2018-11-21 22:33:40,959: vrnetlab   INFO     STDERR: qemu-system-x86_64: -monitor tcp:0.0.0.0:4000,server,nowait: Failed to bind socket: Address already in use

Traceback (most recent call last):
  File "/launch.py", line 378, in <module>
    ia.start()
  File "/vrnetlab.py", line 321, in start
    vm.work()
  File "/vrnetlab.py", line 258, in work
    self.check_qemu()
  File "/vrnetlab.py", line 278, in check_qemu
    outs, errs = self.p.communicate(timeout=1)
  File "/usr/lib/python3.5/subprocess.py", line 801, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1437, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/usr/lib/python3.5/selectors.py", line 351, in register
    key = super().register(fileobj, events, data)
  File "/usr/lib/python3.5/selectors.py", line 237, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/usr/lib/python3.5/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib/python3.5/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.TextIOWrapper name=3 encoding='ANSI_X3.4-1968'>
kll@nuc:~/para/projects/2018-11-21_-_kubernetes-for-vrnetlab-ci$ 
```

I have --trace on and we can see that qemu borked resulting in this..

I also see now that you actually have STDOUT and STDERR lines, but they're empty. I'm still guessing qemu died somehow. Not sure exactly why nor how to tell.
