### ISSUE TITLE
vMX 16.X doesnt build

### ISSUE THREAD

**Issue by job** [plajjan/vrnetlab#21]
```
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Processing triggers for ca-certificates (20141019+deb8u1) ...
Updating certificates in /etc/ssl/certs... 174 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
Processing triggers for sgml-base (1.26+nmu4) ...
 ---> d3fd7302ac99
Removing intermediate container 1ab53b3a4bfb
Step 5 : ARG IMAGE
 ---> Running in ec20630d13fe
 ---> 693addb228a1
Removing intermediate container ec20630d13fe
Step 6 : COPY $IMAGE /vmx.tgz
 ---> 6eb1d568022c
Removing intermediate container 639d4e8abc6f
Step 7 : COPY install_vmx.sh /
 ---> 4fa144fbef14
Removing intermediate container bf0fee94f8ca
Step 8 : RUN /install_vmx.sh
 ---> Running in 4c9ad9bd1be9
Installing Juniper vMX
vmx-16.1R1.7/images/vmxhdd.img
vmx-16.1R1.7/images/vFPC-20160617.img
vmx-16.1R1.7/images/metadata_usb.img
'/tmp/vmx-16.1R1.7/images/vmxhdd.img' -> '/vmx/vmxhdd.img'
mv: cannot stat '/tmp/vmx*/images/jinstall64-vmx*img': No such file or directory
'/tmp/vmx-16.1R1.7/images/vFPC-20160617.img' -> '/vmx/vfpc.img'
'/tmp/vmx-16.1R1.7/images/metadata_usb.img' -> '/vmx/metadata_usb.img'
removed '/vmx.tgz'
removed directory: '/tmp/vmx-16.1R1.7/images'
removed directory: '/tmp/vmx-16.1R1.7'
removed directory: '/tmp'
```

Something changed between 15.1 and 16.1

**Comment by job** [comment]
Unsure if local issue or related to the fact that this does not build:

Additional info:

```
[root@dockerlab ~]# docker run -i --rm --name 16.1R1.7 vr-vmx:16.1R1.7
add bridge failed: Operation not permitted
qemu-system-x86_64: -netdev tap,ifname=vcp1,id=vcp1,script=no,downscript=no: could not open /dev/net/tun: No such file or directory
qemu-system-x86_64: -netdev tap,ifname=vcp1,id=vcp1,script=no,downscript=no: Device 'tap' could not be initialized
Could not access KVM kernel module: No such file or directory
failed to initialize KVM: No such file or directory
interface vcp1 does not exist!
interface vfpc1 does not exist!
Cannot find device "int_cp"
Cannot find device "vcp1"
Cannot find device "vfpc1"
Reaping child
Reaping child
Reaping child
Reaping child
Reaping child
Reaping child
Reaping child
Reaping child
Reaping child
Reaping child
Traceback (most recent call last):
  File "/launch_vmx.py", line 242, in <module>
    vr.start()
  File "/launch_vmx.py", line 77, in start
    self.bootstrap_init()
  File "/launch_vmx.py", line 149, in bootstrap_init
    self.tn = telnetlib.Telnet("127.0.0.1", 5000)
  File "/usr/lib/python3.4/telnetlib.py", line 221, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.4/telnetlib.py", line 237, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[root@dockerlab ~]#
```

**Comment by plajjan** [comment]
Seems to be two things. The .img file has moved so we need to fix that. Secondly you are running the container without --privileged which is probably the reason it fails in creating bridges and stuff like that.

**Comment by plajjan** [comment]
I think the XRv & sros images can be run without --privileged, although significantly slower as it wouldn't use hardware virt support. For vMX we can't since we are building a bridge to connect the VCP and vFPC. I think we can replace that bridge with a UDP/TCP interface and thus be able to run without --privileged too.

**Comment by job** [comment]
I recommend you test with these publicly downloadable vMXs files

```
[root@dockerlab vmx]# md5sum *.tgz
8f06a8ac057f303bf1614bace28d858a  vmx-14.1R5.4-1.tgz
eb128cffde6ab29fdb27b2f52301c5f9  vmx-bundle-15.1F6.9.tgz
d96766848731c12c0492e3ae2349b426  vmx-bundle-16.1R1.7.tgz
```

**Comment by plajjan** [comment]
Try now! :)
