### ISSUE TITLE
Syntax error when building image inside csr folder

### ISSUE THREAD

**Issue by keeganb2000** [plajjan/vrnetlab#277]
I'm seeing a syntax error on this line

```
  File "/vrnetlab.py", line 51
    logging.getLogger().info(f"Delaying VM boot of by {delay} seconds")
```

```
sudo make docker-image
Makefile:15: warning: overriding recipe for target `docker-pre-build'
../makefile.include:18: warning: ignoring old recipe for target `docker-pre-build'
for IMAGE in csr1000v-universalk9.16.04.01-serial.qcow2; do \
	echo "Making $IMAGE"; \
	make IMAGE=$IMAGE docker-build; \
done
Making csr1000v-universalk9.16.04.01-serial.qcow2
make[1]: Entering directory `/home/ec2-user/automation/vrnetlab/csr'
Makefile:15: warning: overriding recipe for target `docker-pre-build'
../makefile.include:18: warning: ignoring old recipe for target `docker-pre-build'
rm -f docker/*.qcow2* docker/*.tgz* docker/*.vmdk* docker/*.iso
cat cidfile | xargs --no-run-if-empty docker rm -f
dfca702fa257091a004023a4f50d0cfdd66d3a6824b1c64e8d3f6a91dfdefec1
rm cidfile
Building docker image using csr1000v-universalk9.16.04.01-serial.qcow2 as vrnetlab/vr-csr:16.04.01
cp ../common/* docker/
make IMAGE=$IMAGE docker-build-image-copy
make[2]: Entering directory `/home/ec2-user/automation/vrnetlab/csr'
Makefile:15: warning: overriding recipe for target `docker-pre-build'
../makefile.include:18: warning: ignoring old recipe for target `docker-pre-build'
cp csr1000v-universalk9.16.04.01-serial.qcow2* docker/
make[2]: Leaving directory `/home/ec2-user/automation/vrnetlab/csr'
(cd docker; docker build --build-arg http_proxy= --build-arg https_proxy= --build-arg IMAGE=csr1000v-universalk9.16.04.01-serial.qcow2 -t vrnetlab/vr-csr:16.04.01 .)
Sending build context to Docker daemon  1.458GB
Step 1/10 : FROM debian:stretch
 ---> 066e7b4151cf
Step 2/10 : MAINTAINER Kristian Larsson <kristian@spritelink.net>
 ---> Using cache
 ---> 8b88b4ad1a30
Step 3/10 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 59c2e47f753a
Step 4/10 : RUN apt-get update -qy  && apt-get upgrade -qy  && apt-get install -y     bridge-utils     iproute2     python3-ipy     socat     qemu-kvm     genisoimage  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> aa17bb8ebc2a
Step 5/10 : ARG IMAGE
 ---> Using cache
 ---> 1f7f35367e6a
Step 6/10 : COPY $IMAGE* /
 ---> 7f23530b844f
Step 7/10 : COPY *.py /
 ---> fe1ecc2c2876
Step 8/10 : EXPOSE 22 161/udp 830 5000 10000-10099
 ---> Running in 906beb4f9f5c
Removing intermediate container 906beb4f9f5c
 ---> 8aa2cef0a465
Step 9/10 : HEALTHCHECK CMD ["/healthcheck.py"]
 ---> Running in 62470c58f800
Removing intermediate container 62470c58f800
 ---> ebb934e92371
Step 10/10 : ENTRYPOINT ["/launch.py"]
 ---> Running in b284075e8218
Removing intermediate container b284075e8218
 ---> 027f00c1e672
Successfully built 027f00c1e672
Successfully tagged vrnetlab/vr-csr:16.04.01
docker run --cidfile cidfile --privileged vrnetlab/vr-csr:16.04.01 --trace --install
Traceback (most recent call last):
  File "/launch.py", line 13, in <module>
    import vrnetlab
  File "/vrnetlab.py", line 51
    logging.getLogger().info(f"Delaying VM boot of by {delay} seconds")
                                                                     ^
SyntaxError: invalid syntax
make[1]: *** [docker-build] Error 1
make[1]: Leaving directory `/home/ec2-user/automation/vrnetlab/csr'
make: *** [docker-image] Error 2
```

**Comment by mzagozen** [comment]
This looks like an issue for the containerlab (hellt/vrnetlab) fork according to the source: https://github.com/hellt/vrnetlab/blob/master/common/vrnetlab.py#L53. FWIW I don't see anything incorrect in the current version of the file. @keeganb2000 if you're still seeing the error please open an issue in https://github.com/hellt/vrnetlab
